import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Utilities/Navbar'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'OTAKUVISTA',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Navbar/>
          {children}
      </body>
    </html>
  )
}
export default RootLayout
export { metadata }
