import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'OtakuVista',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <div>
        <h1>OtakuVista</h1>
      </div>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
export default RootLayout
export { metadata }
