import { Gabarito } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const gabarito = Gabarito({ subsets: ['latin'] })

const metadata = {
  title: 'OTAKUVISTA',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${gabarito.className} bg-color-dark bg`}>
          <Navbar/>
          {children}
      </body>
    </html>
  )
}
export default RootLayout
export { metadata }
